import { formUiConfig } from '../interfaces/formUi.interface';

export const FORM_UI_CONFIG: formUiConfig = {
  title: 'إضافة إتفاقية جديدة',
  submitText: 'حفظ',
  cancelText: 'إلغاء',
  fields: [
    {
      name: 'agreementName',
      label: 'إسم الإتفاق',
      type: 'text',
      required: true,
      placeholder: 'ادخل إسم الإتفاق',
      colSpan: 1,
    },
    {
      name: 'stage',
      label: 'المرحلة',
      type: 'select',
      required: true,
      placeholder: 'إختر المرحلة',
      colSpan: 1,
      options: [
        { value: 'تأهيل', label: 'تأهيل' },
        { value: 'عرض أولي', label: 'عرض أولي' },
        { value: 'عرض مفصل', label: 'عرض مفصل' },
        { value: 'مفاوضات', label: 'مفاوضات' },
        { value: 'إغلاق', label: 'إغلاق' },
      ],
    },
    {
      name: 'status',
      label: 'الحالة',
      type: 'select',
      required: true,
      placeholder: 'إختر الحالة',
      colSpan: 1,
      options: [
        { value: 'نشط', label: 'نشط' },
        { value: 'معلق', label: 'معلق' },
        { value: 'مكتمل', label: 'مكتمل' },
        { value: 'ملغي', label: 'ملغي' },
      ],
    },
    {
      name: 'contractValue',
      label: 'قيمة العقد',
      type: 'number',
      required: true,
      placeholder: 'ادخل قيمة العقد',
      colSpan: 1,
    },
    {
      name: 'period',
      label: 'الفترة',
      type: 'select',
      required: true,
      placeholder: 'إختر الفترة',
      colSpan: 1,
      options: [
        { value: 'شهر', label: 'شهر' },
        { value: '3 أشهر', label: '3 أشهر' },
        { value: '6 أشهر', label: '6 أشهر' },
        { value: 'سنة', label: 'سنة' },
        { value: 'سنتان', label: 'سنتان' },
        { value: '3 سنوات', label: '3 سنوات' },
      ],
    },
    {
      name: 'project',
      label: 'المشروع',
      type: 'text',
      required: true,
      placeholder: 'إدخل إسم المشروع',
      colSpan: 1,
    },
    {
      name: 'dueDate',
      label: 'تاريخ الإستحقاق',
      type: 'date',
      required: true,
      colSpan: 1,
    },
    {
      name: 'employeeName',
      label: 'اسم الموظف المسؤول (طرف أول)',
      type: 'text',
      required: true,
      placeholder: 'ادخل إسم الموظف',
      colSpan: 1,
    },
    {
      name: 'priority',
      label: 'الأولوية',
      type: 'select',
      required: true,
      placeholder: 'إختر الأولوية',
      colSpan: 1,
      options: [
        { value: 'منخفض', label: 'منخفض' },
        { value: 'متوسط', label: 'متوسط' },
        { value: 'عالي', label: 'عالي' },
        { value: 'قصوي', label: 'قصوي' },
      ],
    },
    {
      name: 'followUpDate',
      label: 'تاريخ المتابعة',
      type: 'date',
      required: true,
      colSpan: 1,
    },
    {
      name: 'clientName',
      label: 'إسم العميل (طرف ثاني)',
      type: 'text',
      required: true,
      placeholder: 'ادخل إسم العميل',
      colSpan: 1,
    },
    {
      name: 'expectedClosingDate',
      label: 'تاريخ الإغلاق المتوقع',
      type: 'date',
      required: true,
      colSpan: 1,
    },

    {
      name: 'source',
      label: 'المصدر',
      type: 'select',
      required: true,
      placeholder: 'إختر المصدر',
      colSpan: 1,
      options: [
        { value: 'موقع إلكتروني', label: 'موقع إلكتروني' },
        { value: 'إعلان', label: 'إعلان' },
        { value: 'توصية', label: 'توصية' },
        { value: 'مكالمة هاتفية', label: 'مكالمة هاتفية' },
        { value: 'بريد إلكتروني', label: 'بريد إلكتروني' },
        { value: 'أخرى', label: 'أخرى' },
      ],
    },
    {
      name: 'description',
      label: 'الوصف (إختياري)',
      type: 'textarea',
      required: false,
      placeholder: 'ادخل وصف الإتفاق',
      colSpan: 2,
    },
  ],
};
