import { formUiConfig } from '../interfaces/formUi.interface';

export const COMPANY_FORM_CONFIG: formUiConfig = {
  title: 'إضافة شركة جديدة',
  submitText: 'حفظ',
  cancelText: 'إلغاء',
  fields: [
    {
      name: 'companyName',
      label: 'إسم الشركة',
      type: 'text',
      placeholder: 'ادخل اسم الشركة',
      required: true,
      colSpan: 1,
    },
    {
      name: 'email',
      label: 'البريد الإلكتروني',
      type: 'email',
      placeholder: 'ادخل البريد الإلكتروني',
      required: true,
      colSpan: 1,
    },
    {
      name: 'phoneNumber',
      label: 'رقم الهاتف',
      type: 'two-inputs',
      required: true,
      colSpan: 1,
      input2: {
        name: 'phonePrefix',
        label: '',
        type: 'text',
        placeholder: '',
        required: false,
        disabled: true,
      },
      input1: {
        name: 'phoneNumber',
        label: '',
        type: 'text',
        placeholder: 'أدخل رقم الهاتف',
        required: true,
      },
    },
    {
      name: 'industeryId',
      label: 'الصناعة',
      type: 'select',
      placeholder: 'إختر الصناعة',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'companySizeId',
      label: 'حجم الشركة',
      type: 'select',
      placeholder: 'إختر حجم الشركة',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'companyStageId',
      label: 'المرحلة',
      type: 'select',
      placeholder: 'إختر المرحلة',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'ownershipId',
      label: 'الملكية',
      type: 'select',
      placeholder: 'إختر الملكية',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'counteryId',
      label: 'الدولة',
      type: 'select',
      placeholder: 'إختر الدولة',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'cityId',
      label: 'المدينة',
      type: 'select',
      placeholder: 'إختر المدينة',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'addressLine',
      label: 'العنوان',
      type: 'textarea',
      placeholder: 'ادخل العنوان',
      required: false,
      colSpan: 3,
    },
  ],
};
