import { formUiConfig } from '../interfaces/formUi.interface';

export const COMPANY_FORM_CONFIG: formUiConfig = {
  title: 'إضافة شركة جديدة',
  submitText: 'حفظ',
  cancelText: 'إلغاء',
  fields: [
    {
      name: 'companyName',
      label: 'إسم الشركة',
      type: 'text',
      placeholder: 'ادخل اسم الشركة',
      required: true,
      colSpan: 1,
    },
    {
      name: 'email',
      label: 'البريد الإلكتروني',
      type: 'email',
      placeholder: 'ادخل البريد الإلكتروني',
      required: true,
      colSpan: 1,
    },
    {
      name: 'location',
      label: 'الموقع',
      type: 'text',
      placeholder: 'ادخل الموقع',
      required: true,
      colSpan: 1,
    },
    {
      name: 'agreement',
      label: 'الإتفاق',
      type: 'select',
      placeholder: 'إختر الإتفاق',
      required: true,
      colSpan: 1,
      options: [
        { value: 'standard', label: 'اتفاقية قياسية' },
        { value: 'premium', label: 'اتفاقية مميزة' },
        { value: 'custom', label: 'اتفاقية مخصصة' },
      ],
    },
    {
      name: 'rating',
      label: 'التقييم',
      type: 'select',
      placeholder: 'إختر التقييم',
      required: true,
      colSpan: 1,
      options: [
        { value: '1', label: 'نجمة واحدة' },
        { value: '2', label: 'نجمتان' },
        { value: '3', label: 'ثلاث نجوم' },
        { value: '4', label: 'أربع نجوم' },
        { value: '5', label: 'خمس نجوم' },
      ],
    },
    {
      name: 'industry',
      label: 'الصناعة',
      type: 'select',
      placeholder: 'إختر الصناعة',
      required: true,
      colSpan: 1,
      options: [
        { value: 'technology', label: 'التكنولوجيا' },
        { value: 'construction', label: 'البناء والتشييد' },
        { value: 'commerce', label: 'التجارة' },
        { value: 'healthcare', label: 'الرعاية الصحية' },
        { value: 'education', label: 'التعليم' },
        { value: 'finance', label: 'الخدمات المالية' },
      ],
    },
    {
      name: 'phoneNumber',
      label: 'رقم التليفون',
      type: 'text',
      placeholder: 'أدخل رقم التليفون',
      required: true,
      colSpan: 1,
    },
    {
      name: 'responsibleEmployee',
      label: 'الموظف المسؤول',
      type: 'select',
      placeholder: 'إختر الموظف',
      required: true,
      colSpan: 1,
      options: [
        { value: 'emp1', label: 'أحمد محمد' },
        { value: 'emp2', label: 'فاطمة علي' },
        { value: 'emp3', label: 'محمد حسن' },
        { value: 'emp4', label: 'نور الدين' },
      ],
    },
    {
      name: 'source',
      label: 'المصدر',
      type: 'select',
      placeholder: 'إختر المصدر',
      required: true,
      colSpan: 1,
      options: [
        { value: 'website', label: 'الموقع الإلكتروني' },
        { value: 'referral', label: 'إحالة' },
        { value: 'social', label: 'وسائل التواصل الاجتماعي' },
        { value: 'advertisement', label: 'إعلان' },
        { value: 'other', label: 'أخرى' },
      ],
    },
    {
      name: 'notes',
      label: 'ملاحظات',
      type: 'textarea',
      placeholder: 'إدخل الملاحظات',
      required: false,
      colSpan: 2,
    },
  ],
};
