import { formUiConfig } from '../interfaces/formUi.interface';

export const EMPLOYEE_FORM_CONFIG: formUiConfig = {
  title: 'إضافة موظف',
  submitText: 'حفظ',
  cancelText: 'إلغاء',
  fields: [
    {
      name: 'name',
      label: 'اسم الموظف',
      type: 'text',
      placeholder: 'ادخل اسم الموظف',
      required: true,
      colSpan: 1,
    },
    {
      name: 'phoneNumber',
      label: 'رقم الموبايل',
      type: 'text',
      placeholder: 'ادخل رقم الموبايل',
      required: true,
      colSpan: 1,
    },
    {
      name: 'email',
      label: 'البريد الالكتروني',
      type: 'email',
      placeholder: 'ادخل البريد الالكتروني',
      required: true,
      colSpan: 1,
    },
    {
      name: 'empCode',
      label: 'كود الموظف',
      type: 'text',
      placeholder: 'ادخل كود الموظف',
      required: false,
      colSpan: 1,
    },
    {
      name: 'position',
      label: 'المسمى الوظيفي',
      type: 'select',
      placeholder: 'ادخل المسمى الوظيفي',
      required: true,
      colSpan: 1,
      options: [
        { value: 'manager', label: 'مدير' },
        { value: 'developer', label: 'قائد فريق' },
        { value: 'designer', label: 'موظف' },
        { value: 'sales', label: 'متدرب' },
      ],
    },
    {
      name: 'dateOfBirth',
      label: 'تاريخ الميلاد',
      type: 'date',
      placeholder: 'ادخل تاريخ الميلاد',
      required: true,
      colSpan: 1,
    },
    {
      name: 'hireDate',
      label: 'تاريخ الإنضمام',
      type: 'date',
      placeholder: 'ادخل تاريخ الإنضمام',
      required: true,
      colSpan: 1,
    },

    {
      name: 'departmentId',
      label: 'القسم',
      type: 'select',
      placeholder: 'اختر القسم',
      required: true,
      colSpan: 1,
      options: [],
    },
    {
      name: 'empUserId',
      label: 'المستخدم',
      type: 'select',
      placeholder: 'اختر المستخدم',
      required: false,
      colSpan: 1,
      options: [],
    },
    {
      name: 'salary',
      label: 'المرتب',
      type: 'number',
      placeholder: 'ادخل المرتب',
      required: true,
      colSpan: 1,
    },
    {
      name: 'gender',
      label: 'الجنس',
      type: 'radio',
      required: true,
      options: [
        { value: 'male', label: 'ذكر' },
        { value: 'female', label: 'أنثى' },
      ],
    },
    {
      name: 'isActive',
      label: 'الحالة',
      type: 'radio',
      required: true,
      colSpan: 1,
      options: [
        { value: true, label: 'نشط' },
        { value: false, label: 'غير نشط' },
      ],
    },
    {
      name: 'file',
      label: 'صورة الموظف',
      type: 'file',
      accept: 'image/*',
      colSpan: 3,
      required: false,
    },
  ],
};
