import { formUiConfig } from '../interfaces/formUi.interface';

export const FORM_UI_CONFIG: formUiConfig = {
  title: 'تعديل الفاتورة',
  submitText: 'حفظ',
  cancelText: 'إلغاء',
  fields: [
    {
      name: 'clientName',
      label: 'اسم العميل',
      type: 'text',
      required: true,
      placeholder: 'ادخل اسم العميل',
      colSpan: 1,
    },
    {
      name: 'clientEmail',
      label: 'البريد الإلكتروني',
      type: 'email',
      required: true,
      placeholder: 'ادخل البريد الإلكتروني',
      colSpan: 1,
    },
    {
      name: 'clientPhone',
      label: 'رقم الهاتف',
      type: 'text',
      required: true,
      placeholder: 'ادخل رقم الهاتف',
      colSpan: 1,
    },
    {
      name: 'totalprices',
      label: 'المبلغ الكلي',
      type: 'number',
      required: true,
      placeholder: 'ادخل المبلغ الكلي',
      colSpan: 1,
    },
    {
      name: 'paymentMethod',
      label: 'طريقة الدفع',
      type: 'select',
      required: true,
      placeholder: 'اختر طريقة الدفع',
      colSpan: 1,
      options: [
        { value: 'تحويل بنكي', label: 'تحويل بنكي' },
        { value: 'بطاقة ائتمان', label: 'بطاقة ائتمان' },
        { value: 'نقدي', label: 'نقدي' },
        { value: 'شيك', label: 'شيك' },
        { value: 'أخرى', label: 'أخرى' },
      ],
    },
    {
      name: 'paidAmount',
      label: 'المبلغ المدفوع',
      type: 'number',
      required: true,
      placeholder: 'ادخل المبلغ المدفوع',
      colSpan: 1,
    },
    {
      name: 'paymentStatus',
      label: 'حالة الدفع',
      type: 'select',
      required: true,
      placeholder: 'اختر حالة الدفع',
      colSpan: 1,
      options: [
        { value: 'مدفوعة', label: 'مدفوعة' },
        { value: 'متأخرة', label: 'متأخرة' },
        { value: 'قيد المراجعة', label: 'قيد المراجعة' },
        { value: 'غير مدفوعة', label: 'غير مدفوعة' },
        { value: 'ملغاة', label: 'ملغاة' },
      ],
    },
  ],
};
